ALTER TABLE orders ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS pincode TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_orders_city ON orders (city) WHERE city <> '';
